import{a as q,S as v,i as c}from"./assets/vendor-hwdYKDic.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const E="48830775-40ff68ea61f2bc47ba43ee541",S="https://pixabay.com/api/",P=40;async function g(r,e){const s=`${S}?key=${E}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&page=${e}&per_page=${P}`;try{return(await q.get(s)).data}catch(n){throw console.error("Error fetching data from Pixabay API:",n),n}}function d(r,e=!1){const s=document.querySelector(".gallery");e&&(s.innerHTML="");const n=r.map(({largeImageURL:o,webformatURL:u,tags:p,likes:y,views:L,comments:b,downloads:w})=>`
      <a href="${o}" class="gallery-item">
        <img src="${u}" alt="${p}" />
        <div class="image-info">
          <p class="image-title"><strong>Likes:</strong> ${y}</p>
          <p class="image-title"><strong>Views:</strong> ${L}</p>
          <p class="image-title"><strong>Comments:</strong> ${b}</p>
          <p class="image-title"><strong>Downloads:</strong> ${w}</p>
        </div>
      </a>`).join("");s.insertAdjacentHTML("beforeend",n),new v(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom",overlayOpacity:1,showCounter:!1}).refresh()}function $(){var e;const r=((e=document.querySelector(".gallery-item"))==null?void 0:e.getBoundingClientRect().height)||100;window.scrollBy({top:r*2,behavior:"smooth"})}const a={form:document.querySelector(".search-form"),input:document.querySelector(".search-input"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-btn")},i={query:"",page:1,totalHits:0};function m(){a.loader.classList.remove("hidden")}function f(){a.loader.classList.add("hidden")}function h(){a.loadMoreBtn.classList.remove("hidden")}function l(){a.loadMoreBtn.classList.add("hidden")}a.form.addEventListener("submit",async r=>{if(r.preventDefault(),i.query=a.input.value.trim(),i.page=1,!i.query){c.error({title:"Error",message:"Please enter a search term!",position:"topRight",timeout:2e3}),a.input.value="",d([],!0),l();return}m(),l();try{const{hits:e,totalHits:s}=await g(i.query,i.page);i.totalHits=s,d([],!0),e.length===0?c.info({title:"Oops!",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3}):(d(e,!0),e.length<i.totalHits&&h())}catch(e){c.error({title:"Error",message:"Something went wrong! Please try again later.",position:"topRight",timeout:3e3}),d([],!0),l(),console.error("Error fetching images:",e)}finally{f()}});a.loadMoreBtn.addEventListener("click",async()=>{i.page+=1,l(),m();try{const{hits:r}=await g(i.query,i.page);if(r.length===0){c.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3}),l();return}d(r,!1),$(),r.length<40?(l(),c.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"bottomRight",timeout:3e3})):h()}catch(r){c.error({title:"Error",message:"Something went wrong! Please try again later.",position:"topRight",timeout:3e3}),console.error("Error fetching images:",r),l()}finally{f()}});
//# sourceMappingURL=index.js.map
