import{a as w,S as q,i as l}from"./assets/vendor-hwdYKDic.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const v="48830775-40ff68ea61f2bc47ba43ee541",E="https://pixabay.com/api/",S=40;async function m(r,e){const s=`${E}?key=${v}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&page=${e}&per_page=${S}`;try{return(await w.get(s)).data}catch(n){throw console.error("Error fetching data from Pixabay API:",n),n}}function u(r,e=!1){const s=document.querySelector(".gallery");e&&(s.innerHTML="");const n=r.map(({largeImageURL:o,webformatURL:c,tags:h,likes:p,views:y,comments:L,downloads:b})=>`
      <a href="${o}" class="gallery-item">
        <img src="${c}" alt="${h}" />
        <div class="image-info">
          <p class="image-title"><strong>Likes:</strong> ${p}</p>
          <p class="image-title"><strong>Views:</strong> ${y}</p>
          <p class="image-title"><strong>Comments:</strong> ${L}</p>
          <p class="image-title"><strong>Downloads:</strong> ${b}</p>
        </div>
      </a>`).join("");s.insertAdjacentHTML("beforeend",n),new q(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom",overlayOpacity:1,showCounter:!1}).refresh()}function P(){var e;const r=((e=document.querySelector(".gallery-item"))==null?void 0:e.getBoundingClientRect().height)||100;window.scrollBy({top:r*2,behavior:"smooth"})}const a={form:document.querySelector(".search-form"),input:document.querySelector(".search-input"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-btn")},i={query:"",page:1,totalHits:0};function d(){a.loader.classList.remove("hidden")}function $(){a.loader.classList.add("hidden")}function f(){a.loadMoreBtn.classList.remove("hidden")}function g(){a.loadMoreBtn.classList.add("hidden")}a.form.addEventListener("submit",async r=>{if(r.preventDefault(),i.query=a.input.value.trim(),i.page=1,!i.query){l.error({title:"Error",message:"Please enter a search term!",position:"topRight",timeout:2e3}),a.input.value="",u([],!0);return}d(),g();try{const{hits:e,totalHits:s}=await m(i.query,i.page);i.totalHits=s,u([],!0),e.length===0?l.info({title:"Oops!",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3}):(u(e,!0),e.length<i.totalHits&&f())}catch(e){l.error({title:"Error",message:"Something went wrong! Please try again later.",position:"topRight",timeout:3e3}),u([],!0),console.error("Error fetching images:",e)}finally{$()}});a.loadMoreBtn.addEventListener("click",async()=>{i.page+=1,g(),d();try{const{hits:r}=await m(i.query,i.page);if(r.length===0){l.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3});return}u(r,!1),P(),r.length<40?(g(),l.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"bottomRight",timeout:3e3})):f()}catch(r){l.error({title:"Error",message:"Something went wrong! Please try again later.",position:"topRight",timeout:3e3}),console.error("Error fetching images:",r)}finally{d()}});
//# sourceMappingURL=index.js.map
